services:
  camel-db:
    image: postgres:16.4
    environment:
      POSTGRES_DB: camel
      POSTGRES_USER: camel_user
      POSTGRES_PASSWORD: camel_pass
    ports:
      - "5432:5432"
    volumes:
      - camel-db-data:/var/lib/postgresql/data

  camel-app:
    image: book-library:local
    ports:
      - "7979:7979"

  camel-gateway:
    image: gateway:local
    ports:
      - "7878:7878"

volumes:
  camel-db-data:
