apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-jobmanager
spec:
  replicas: 1
  selector:
    matchLabels: { app: flink, component: jobmanager }
  template:
    metadata:
      labels: { app: flink, component: jobmanager }
    spec:
      containers:
        - name: jobmanager
          image: flink-kafka:v2
          args: ["jobmanager"]
          env:
            - name: FLINK_PROPERTIES
              value: |
                jobmanager.rpc.address: flink-jobmanager
                jobmanager.rpc.port: 6123
                blob.server.port: 6124
                taskmanager.numberOfTaskSlots: 2
          ports:
            - containerPort: 6123
            - containerPort: 6124
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager
spec:
  selector: { app: flink, component: jobmanager }
  ports:
    - name: rpc
      port: 6123
    - name: blob
      port: 6124
    - name: ui
      port: 8081