apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-taskmanager
spec:
  replicas: 1
  selector:
    matchLabels: { app: flink, component: taskmanager }
  template:
    metadata:
      labels: { app: flink, component: taskmanager }
    spec:
      containers:
        - name: taskmanager
          image: flink-kafka:v2
          args: ["taskmanager"]
          env:
            - name: FLINK_PROPERTIES
              value: |
                jobmanager.rpc.address: flink-jobmanager
                jobmanager.rpc.port: 6123
                taskmanager.numberOfTaskSlots: 2
          ports:
            - containerPort: 6122