apiVersion: kafka.strimzi.io/v1
kind: KafkaBridge
metadata:
  name: my-bridge
  namespace: kafka-bridge-demo
spec:
  replicas: 1
  bootstrapServers: kafka-service.default.svc.cluster.local:9092
  http:
    port: 8080